### PR TITLE
Qt 5.14

### LINKED ISSUE #285: Prismatik doesnt start
Not really sure what happened was working fine but Prismatik just crashed and i cant start now, whenever i try to start via bash returns this:

```
19:23:23:915 Warning: Fail load translation for locale "en_US" pathToLocale ":/translations/en_US"
19:23:23:928 Warning: QObject::connect: No such slot LedDeviceLightpack::ledDeviceUpdateWBAdjustments() in LedDeviceManager.cpp:497
19:23:23:932 Fatal: ASSERT: "highest > 0" in file /usr/include/qt/QtCore/qrandom.h, line 133
```
I tried deleting the main.conf file and running again, but after setting up the leds and colors when the process is finished prismatik just crashed.

**EDIT: Seems the i was able to do a small workaround, used the main branch on aur to install prismatik (i was using the git version) after that i did a new profile, while setting things up as soon as i enabled "Apply color temperature and gamma" the error returned, i did a new profile again without the option restart the pc a few times and was working just fine.**

### PR DESCRIPTION
**Pull request by zomfg**
This replaces deprecated Qt methods with the recommended ones, and I think, fixes #285 (new `assert` in `qrandom.h`)

I'm not able to test on anything else than a mac right now, so fingers crossed for the other two, but it's nothing major

### CODE REVIEW

**Comment by psieg** [comment]
Thanks Sergio :)

ok to test

File: Software/src/GrabConfigWidget.cpp [hunk 1]
```diff
@@ -59,7 +60,7 @@ GrabConfigWidget::~GrabConfigWidget()
 
 void GrabConfigWidget::showConfigFor(QRect widgetGeometry, int buttonCenter)
 {
-	QRect screen = QApplication::desktop()->screenGeometry(widgetGeometry.center());
+	QRect screen = QGuiApplication::screenAt(widgetGeometry.center())->geometry();
```
Comment (psieg) [inline Software/src/GrabConfigWidget.cpp]: This was introduced in 5.10. It breaks build on 16.04 LTS (at least on my CI VM) as far as I can tell and the old version doesn't seem to be deprecated?

Comment (zomfg) [reply Software/src/GrabConfigWidget.cpp]: Oh hi :)
[It is deprecated](https://doc.qt.io/qt-5/qdesktopwidget-obsolete.html#screenGeometry-2) since 5.11, the [one that isn't (yet?)](https://doc.qt.io/qt-5/qdesktopwidget.html#screenGeometry-1) takes a `QWidget*`.

I see the linux CI still uses Qt 5.5, which is 5 years and almost 4 LTS releases old, maybe it can be bumped? (and Qt6 is planned for [the end of the year](https://www.qt.io/blog/2019/08/07/technical-vision-qt-6))

Comment (psieg) [reply Software/src/GrabConfigWidget.cpp]: Hm. 16.04 LTS is supported until Apr 2021, but seems stuck at Qt 5.5. Even upgrading to 18.04 appears to yield 5.9, which wouldn't be enough and I'd rather stay on an LTS version for the CI.

Comment (zomfg) [reply Software/src/GrabConfigWidget.cpp]: maybe there's a ppa for 5.12?
if not, I'm fine with something like this
```cpp
	#if (QT_VERSION >= QT_VERSION_CHECK(5, 10, 0))
	QRect screen = QGuiApplication::screenAt(widgetGeometry.center())->geometry();
	#else
	QApplication::desktop()->screenGeometry(widgetGeometry.center());
	#endif
```

Comment (psieg) [reply Software/src/GrabConfigWidget.cpp]: I'd like to remain compatible with the major Ubuntu LTS release. I'll upgrade the VM to 18.04 but since that's probably not going to fix the issue please add the version switch. Thank you :)

Comment (zomfg) [reply Software/src/GrabConfigWidget.cpp]: Done

**Comment by zomfg** [comment]
On the subject of Qt, some [not so good changes](https://www.qt.io/blog/qt-offering-changes-2020)
